# Generated by Django 4.1.7 on 2023-02-15 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill',
            field=models.IntegerField(default=0, verbose_name='صورت حساب'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('date', models.DateField(default=datetime.date(2023, 2, 16), verbose_name='تاریخ')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer', verbose_name='مسئول')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
            },
        ),
    ]
