# Generated by Django 4.1.7 on 2023-02-15 21:29

from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0-0-0-0-0', max_length=50, verbose_name='کد نوسازی')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('status', models.IntegerField(choices=[(1, 'تخریب'), (2, 'گودبرداری'), (3, 'چینش فندانسیون'), (4, 'بتن ریزی فندانسیون'), (5, 'ستون ریزی'), (6, 'تیر ریزی'), (7, 'درحال ساخت'), (8, 'زمین خالی')], verbose_name='وضعیت پروژه')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='مالک یا سازنده')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه',
            },
        ),
        migrations.CreateModel(
            name='p_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='لطفا تمام فایل های خود را یک جا آپلود کنید', upload_to=works.models.p_document.user_directory_path, verbose_name='اسناد')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'اسناد پروژه',
                'verbose_name_plural': 'اسناد پروژه',
            },
        ),
    ]
