# Generated by Django 4.1.7 on 2023-02-15 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define_services', models.IntegerField(choices=[(1, 'درخواست پروانه'), (2, 'درخواست پایانکار'), (3, 'درخواست انتقال'), (4, 'درخواست تفکیکی'), (5, 'طراحی پلان'), (6, 'متفرقه')], verbose_name='خدمات تعریف شده')),
                ('cost_services', models.ImageField(upload_to='', verbose_name='هزینه')),
                ('description', models.TextField(null=True, verbose_name='خدمات متفرقه')),
                ('date', models.DateField(default=datetime.date(2023, 2, 16), verbose_name='تاریخ درخواست')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
