# Generated by Django 4.1.7 on 2023-02-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='code',
            new_name='code_p',
        ),
        migrations.AddField(
            model_name='project',
            name='code_erg',
            field=models.CharField(default='0', max_length=50, verbose_name='کد ارجاع'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cost_services',
            field=models.IntegerField(verbose_name='هزینه'),
        ),
    ]
