# Generated by Django 4.1.7 on 2023-02-16 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_rename_code_project_code_p_project_code_erg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست'),
        ),
    ]
