# Generated by Django 4.1.7 on 2023-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_services_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'تخریب'), (2, 'گودبرداری'), (3, 'چینش فندانسیون'), (4, 'بتن ریزی فندانسیون'), (5, 'ستون ریزی'), (6, 'تیر ریزی'), (7, 'درحال ساخت'), (8, 'زمین خالی'), (9, 'متفرقه')], verbose_name='وضعیت پروژه'),
        ),
    ]
