# Generated by Django 4.1.7 on 2023-02-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customer_user'),
        ('works', '0005_project_description_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer', verbose_name='سازنده یا مالک'),
            preserve_default=False,
        ),
    ]
