# Generated by Django 4.1.7 on 2023-02-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_services_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='خدمات متفرقه'),
        ),
    ]
